# Generated by Django 3.0.3 on 2020-02-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('speed', models.IntegerField()),
                ('price', models.IntegerField()),
                ('bdix', models.CharField(choices=[('1', '10'), ('2', '20'), ('3', '25'), ('4', '30'), ('5', '40'), ('6', '50'), ('7', '70'), ('8', '100')], default='6', max_length=10)),
                ('youtube', models.CharField(choices=[('1', '10'), ('2', '20'), ('3', '25'), ('4', '30'), ('5', '40'), ('6', '50'), ('7', '70'), ('8', '100')], default='6', max_length=10)),
                ('facebook', models.CharField(choices=[('1', '10'), ('2', '20'), ('3', '25'), ('4', '30'), ('5', '40'), ('6', '50'), ('7', '70'), ('8', '100')], default='6', max_length=10)),
                ('ftp', models.CharField(choices=[('1', '10'), ('2', '20'), ('3', '25'), ('4', '30'), ('5', '40'), ('6', '50'), ('7', '70'), ('8', '100')], default='8', max_length=10)),
                ('is_pub', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('installation_charge', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Package')),
            ],
        ),
    ]
