# Generated by Django 3.0.3 on 2020-02-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionshift',
            old_name='done',
            new_name='is_done',
        ),
    ]
