# Generated by Django 3.0.3 on 2020-03-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freereference',
            name='mobile_recharge',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='mobile_recharge',
            field=models.BooleanField(default=True),
        ),
    ]
