# Generated by Django 3.0.3 on 2020-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspentionpermanently',
            name='device_collect_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
