# Generated by Django 3.0.3 on 2020-02-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suspention', '0002_suspentionpermanently_device_collect_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspentionpermanently',
            old_name='approve',
            new_name='is_done',
        ),
    ]
