# Generated by Django 3.0.3 on 2020-03-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Migrate',
        ),
    ]
