# Generated by Django 3.0.3 on 2020-02-18 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('pn_number', models.IntegerField()),
                ('birth_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Active'), ('3', 'Hold'), ('4', 'Closed')], default='1', max_length=20)),
                ('zip_code', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=800)),
                ('ref_by', models.CharField(blank=True, max_length=50)),
                ('active_on', models.DateField(blank=True)),
                ('expired_at', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.Distic')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.Package')),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.Thana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
