# Generated by Django 3.0.3 on 2020-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='active_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
